# Pandas
whenever a structured data is required in in-memory (RAM)

## pandas - data structures
- Series - Stores one column data
- Data Frame (2d table)

In [3]:
# !pip install pandas

In [4]:
import pandas as pd

#store employee name and hike
hikes = pd.Series([2, 35, 4, 10, 20.5],
                    index=['Raj', 'Ram', 'Rahul', 'Arun', 'Arjun'],
                    name='EmplyeeHike')

print(hikes)

Raj       2.0
Ram      35.0
Rahul     4.0
Arun     10.0
Arjun    20.5
Name: EmplyeeHike, dtype: float64

In [5]:
hk = hikes > 6 # Boolean masking
hikes[hk]

Ram      35.0
Arun     10.0
Arjun    20.5
Name: EmplyeeHike, dtype: float64

In [6]:
data = {
    'Name' : ['Ravi', 'Shankar', 'Chekkelar', 'Gowtham'],
    'Age' : [20, 25, 22, 23],
    'Experience' : [2, 2.5, 3, 2]
}

print(data)

df = pd.DataFrame(data)
print(df)

{'Name': ['Ravi', 'Shankar', 'Chekkelar', 'Gowtham'], 'Age': [20, 25, 22, 23], 'Experience': [2, 2.5, 3, 2]}
        Name  Age  Experience
0       Ravi   20         2.0
1    Shankar   25         2.5
2  Chekkelar   22         3.0
3    Gowtham   23         2.0

In [7]:
df.head() # prints the first 5 rows

        Name  Age  Experience
0       Ravi   20         2.0
1    Shankar   25         2.5
2  Chekkelar   22         3.0
3    Gowtham   23         2.0

In [8]:
df.head(2) # prints first 2 rows

      Name  Age  Experience
0     Ravi   20         2.0
1  Shankar   25         2.5

In [9]:
df.tail(2) # prints last 2 rows

        Name  Age  Experience
2  Chekkelar   22         3.0
3    Gowtham   23         2.0

In [10]:
print('shape\n', df.shape)
print('data type\n', df.dtypes)
print('describe\n', df.describe())
print('check any empty rows\n', df.info())

shape
 (4, 3)
data type
 Name              str
Age             int64
Experience    float64
dtype: object
describe
              Age  Experience
count   4.000000    4.000000
mean   22.500000    2.375000
std     2.081666    0.478714
min    20.000000    2.000000
25%    21.500000    2.000000
50%    22.500000    2.250000
75%    23.500000    2.625000
max    25.000000    3.000000
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      str
 1   Age         4 non-null      int64
 2   Experience  4 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 228.0 bytes
check any empty rows
 None

In [11]:
import numpy as np

In [26]:
n = 50
df1 = pd.DataFrame({
    'emp_id' : range(1001,1001+n),
    'name' : [f'Employee_{i}' for i in range(n)],
    'age' : np.random.randint(25, 40, n),
    'dept' : np.random.choice(['Engineering','HR','Sales'], n),
    'rating' : np.random.choice([2, 3, 4, 5, 1], n),
    'salary' : np.random.randint(40000, 85000, n)
})

print(df1)

    emp_id         name  age         dept  rating  salary
0     1001   Employee_0   29  Engineering       1   46679
1     1002   Employee_1   29        Sales       5   69939
2     1003   Employee_2   26        Sales       1   65456
3     1004   Employee_3   37  Engineering       2   41191
4     1005   Employee_4   32  Engineering       2   44018
5     1006   Employee_5   27        Sales       3   65522
6     1007   Employee_6   30           HR       3   81230
7     1008   Employee_7   34        Sales       1   56036
8     1009   Employee_8   36        Sales       2   40233
9     1010   Employee_9   27        Sales       3   51094
10    1011  Employee_10   25           HR       2   41610
11    1012  Employee_11   25           HR       1   68772
12    1013  Employee_12   28           HR       5   69908
13    1014  Employee_13   33        Sales       2   80691
14    1015  Employee_14   39  Engineering       3   48865
15    1016  Employee_15   36        Sales       1   77948
16    1017  Employee_16   32        Sales       4   42306
17    1018  Employee_17   34  Engineering       2   72348
18    1019  Employee_18   29           HR       3   51676
19    1020  Employee_19   27        Sales       4   70888
20    1021  Employee_20   37  Engineering       1   52481
21    1022  Employee_21   35        Sales       3   72860
22    1023  Employee_22   28  Engineering       2   68735
23    1024  Employee_23   35        Sales       4   43504
24    1025  Employee_24   27           HR       5   58007
25    1026  Employee_25   26           HR       1   78571
26    1027  Employee_26   32        Sales       1   75247
27    1028  Employee_27   37        Sales       3   42252
28    1029  Employee_28   29           HR       5   67255
29    1030  Employee_29   35        Sales       1   42023
30    1031  Employee_30   25           HR       5   69734
31    1032  Employee_31   37  Engineering       2   59538
32    1033  Employee_32   26  Engineering       3   53704
33    1034  Employee_33   29  Engineering       3   83987
34    1035  Employee_34   28  Engineering       2   71836
35    1036  Employee_35   26        Sales       1   67959
36    1037  Employee_36   38  Engineering       2   75015
37    1038  Employee_37   26           HR       3   43060
38    1039  Employee_38   31        Sales       5   70199
39    1040  Employee_39   33  Engineering       4   78306
40    1041  Employee_40   30           HR       1   66622
41    1042  Employee_41   35           HR       4   64845
42    1043  Employee_42   29        Sales       5   58187
43    1044  Employee_43   26           HR       3   63856
44    1045  Employee_44   39        Sales       4   55625
45    1046  Employee_45   34        Sales       4   70355
46    1047  Employee_46   25  Engineering       5   64711
47    1048  Employee_47   31        Sales       3   74207
48    1049  Employee_48   31  Engineering       1   44140
49    1050  Employee_49   26           HR       5   53443

In [13]:
df1['rating'].head() # printing only 1 column and 1st 5 rows

0    1
1    1
2    5
3    1
4    2
Name: rating, dtype: int64

In [14]:
df1[['name', 'rating']].head() # printing specified columns and 1st 5 rows

         name  rating
0  Employee_0       1
1  Employee_1       1
2  Employee_2       5
3  Employee_3       1
4  Employee_4       2

In [15]:
df1.loc[1:3,['name', 'rating']] # printing 3 rows and specified columns

         name  rating
1  Employee_1       1
2  Employee_2       5
3  Employee_3       1

In [16]:
df.iloc[0] # printing 1 row

Name          Ravi
Age             20
Experience     2.0
Name: 0, dtype: object

In [17]:
df1.iloc[0].to_dict() # converting the row into dict

{'emp_id': 1001, 'name': 'Employee_0', 'age': 25, 'dept': 'Sales', 'rating': 1}

In [18]:
df1.iloc[-2:, :3] # printing last 2 row and 3 column

    emp_id         name  age
48    1049  Employee_48   25
49    1050  Employee_49   29

In [19]:
rating_filter = df1['rating'] > 3
df1[rating_filter]

age_filter = df1['age'] > 35
df1[age_filter]

    emp_id         name  age         dept  rating
3     1004   Employee_3   39        Sales       1
12    1013  Employee_12   39           HR       4
13    1014  Employee_13   39        Sales       5
26    1027  Employee_26   37        Sales       1
27    1028  Employee_27   39  Engineering       3
28    1029  Employee_28   36  Engineering       5
31    1032  Employee_31   38  Engineering       5
35    1036  Employee_35   36        Sales       4
39    1040  Employee_39   38  Engineering       2
42    1043  Employee_42   38  Engineering       3
44    1045  Employee_44   39  Engineering       4
46    1047  Employee_46   36  Engineering       3
47    1048  Employee_47   38           HR       4

In [20]:
df1[df1['rating'].between(2, 4)]

    emp_id         name  age         dept  rating
4     1005   Employee_4   32  Engineering       2
5     1006   Employee_5   25        Sales       2
7     1008   Employee_7   28           HR       4
12    1013  Employee_12   39           HR       4
14    1015  Employee_14   28           HR       4
15    1016  Employee_15   25  Engineering       4
16    1017  Employee_16   27           HR       4
17    1018  Employee_17   32  Engineering       2
19    1020  Employee_19   27        Sales       4
20    1021  Employee_20   34           HR       3
21    1022  Employee_21   30           HR       3
22    1023  Employee_22   32           HR       3
23    1024  Employee_23   25  Engineering       2
25    1026  Employee_25   35           HR       4
27    1028  Employee_27   39  Engineering       3
29    1030  Employee_29   33  Engineering       3
30    1031  Employee_30   27        Sales       2
33    1034  Employee_33   29        Sales       2
34    1035  Employee_34   31           HR       2
35    1036  Employee_35   36        Sales       4
36    1037  Employee_36   26        Sales       3
37    1038  Employee_37   29  Engineering       2
38    1039  Employee_38   27  Engineering       4
39    1040  Employee_39   38  Engineering       2
41    1042  Employee_41   33  Engineering       2
42    1043  Employee_42   38  Engineering       3
43    1044  Employee_43   34           HR       3
44    1045  Employee_44   39  Engineering       4
46    1047  Employee_46   36  Engineering       3
47    1048  Employee_47   38           HR       4
48    1049  Employee_48   25        Sales       4
49    1050  Employee_49   29           HR       2

In [24]:
df1[df1['dept'].isin(['HR']) & (df1['age'] > 25)]

    emp_id         name  age dept  rating
7     1008   Employee_7   28   HR       4
9     1010   Employee_9   31   HR       1
12    1013  Employee_12   39   HR       4
14    1015  Employee_14   28   HR       4
16    1017  Employee_16   27   HR       4
20    1021  Employee_20   34   HR       3
21    1022  Employee_21   30   HR       3
22    1023  Employee_22   32   HR       3
25    1026  Employee_25   35   HR       4
32    1033  Employee_32   35   HR       1
34    1035  Employee_34   31   HR       2
40    1041  Employee_40   29   HR       1
43    1044  Employee_43   34   HR       3
45    1046  Employee_45   26   HR       5
47    1048  Employee_47   38   HR       4
49    1050  Employee_49   29   HR       2

## session-2 (continuation of pandas)
how we can add and remove column
how to rename the columns in dataframe

In [ ]:
df1['bonus'] = df1['salary'] * 0.10 # adding new columns
df1.head()

   emp_id        name  age         dept  rating  salary   bonus
0    1001  Employee_0   29  Engineering       1   46679  4667.9
1    1002  Employee_1   29        Sales       5   69939  6993.9
2    1003  Employee_2   26        Sales       1   65456  6545.6
3    1004  Employee_3   37  Engineering       2   41191  4119.1
4    1005  Employee_4   32  Engineering       2   44018  4401.8

In [31]:
exp = np.random.randint(10, 20, n)
df1 = df1.assign(exp_year = exp)
df1.head()

   emp_id        name  age         dept  rating  salary   bonus  exp_year
0    1001  Employee_0   29  Engineering       1   46679  4667.9        12
1    1002  Employee_1   29        Sales       5   69939  6993.9        19
2    1003  Employee_2   26        Sales       1   65456  6545.6        12
3    1004  Employee_3   37  Engineering       2   41191  4119.1        12
4    1005  Employee_4   32  Engineering       2   44018  4401.8        10

In [ ]:
# rename columns
df1 = df1.rename(columns= {'salary' : 'basic_salary'})
df1.head()

,emp_id,name,age,dept,rating,basic_salary,bonus,exp_year
0,1001,Employee_0,29,Engineering,1,46679,4667.9,12
1,1002,Employee_1,29,Sales,5,69939,6993.9,19
2,1003,Employee_2,26,Sales,1,65456,6545.6,12
3,1004,Employee_3,37,Engineering,2,41191,4119.1,12
4,1005,Employee_4,32,Engineering,2,44018,4401.8,10

In [33]:
df1['dummy_col'] = df1['exp_year']
df1.head()

,emp_id,name,age,dept,rating,basic_salary,bonus,exp_year,dummy_col
0,1001,Employee_0,29,Engineering,1,46679,4667.9,12,12
1,1002,Employee_1,29,Sales,5,69939,6993.9,19,19
2,1003,Employee_2,26,Sales,1,65456,6545.6,12,12
3,1004,Employee_3,37,Engineering,2,41191,4119.1,12,12
4,1005,Employee_4,32,Engineering,2,44018,4401.8,10,10

In [ ]:
# delete column
df1.drop(columns=['dummy_col'], inplace=True) # inplace = true will replace in the instance, need not to reassign to the variable df1
df1.head()

# deleting row
# df1 = df1.drop(index=[0,1]) -> this will delete index 0 and 1

,emp_id,name,age,dept,rating,basic_salary,bonus,exp_year
0,1001,Employee_0,29,Engineering,1,46679,4667.9,12
1,1002,Employee_1,29,Sales,5,69939,6993.9,19
2,1003,Employee_2,26,Sales,1,65456,6545.6,12
3,1004,Employee_3,37,Engineering,2,41191,4119.1,12
4,1005,Employee_4,32,Engineering,2,44018,4401.8,10

In [ ]:
emp_data = {
    'Name':['Karan', 'Karthi', 'Madan', 'Madavan', 'Mannar'],
    'Age' : [30, 40, np.nan, 25, np.nan],
    'Salary' : [25000, 60000, 25000, np.nan, 30000],
    'Dept' : [],
    'Score' : []
}

emp_df = pd.DataFrame(emp_data)

df.isna()
df.isna().sum()

emp_df['Salary'].mean()

emp_df_copy = emp_df.copy()

emp_df_copy['Age'] = emp_df_copy['Age'].fillna(emp_df_copy['Age'].mean())
emp_df_copy['Salary'] = emp_df_copy['Salary'].fillna(emp_df_copy['Salary'].mean())
emp_df_copy['Dept'] = emp_df_copy['Salary'].fillna('Unknown')

emp_df_copy.groupby('Dept')['Salary'].sum()

summary = emp_df_copy.groupby('Dept').agg(
    Count_Emp = ('Name', 'count'),
    Mean_Salary = ('Salary', 'mean'),
    Max_Score = ('Score', 'mean'),
    Avg_Salary = ('Salary', 'mean')
).round(1)


# ranking and sorting in dataframe
emp_df_copy.sort_values('Salary', ascending=True)
emp_df_copy.sort_values(['Salary', 'Age'], ascending=[True, False])

{'Name': ['Ravi', 'Shankar', 'Chekkelar', 'Gowtham'],
 'Age': [20, 25, 22, 23],
 'Experience': [2, 2.5, 3, 2]}